export type EvidenceStatus = "Verified" | "Awaiting public file" | "First-person account" | "Pending clarification";
export type EvidenceItem = { id: string; date: string; source: string; category: string; status: EvidenceStatus; title: string; summary: string; publicFile: boolean; publicPath?: string; publicLabel?: string; };

export const evidence: EvidenceItem[] = [
  { id: "OMI-ORDER-001", date: "August 12, 2026", source: "Omi account order record", category: "Order record", status: "Verified", title: "Order #21308 - $203.99 total", summary: "The preserved Omi order record shows an Omi device at $129.00 after a $50.00 discount, a Firmware Developer Kit at $59.99, $15.00 shipping, and a $203.99 total. The public copy redacts contact, shipping, payment, tracking, and order-access details.", publicFile: true, publicPath: "/evidence/orders/OMI-ORDER-001-order-21308-redacted.pdf", publicLabel: "View redacted order record ↗" },
  { id: "OMI-WEB-001", date: "Article dated January 15, 2026", source: "Omi website article screenshot", category: "Website", status: "Verified", title: "Omi article states $199/year and 1,200 free minutes", summary: "The preserved Omi article says the service includes 1,200 minutes of free listening per month and that Unlimited is $199 per year, or about $16 per month with two months free.", publicFile: true, publicPath: "/evidence/website/OMI-WEB-001-sales-article-199-and-1200.png", publicLabel: "View public article screenshot ↗" },
  { id: "OMI-WEB-002", date: "Preserved August 23, 2026", source: "Omi website article screenshot", category: "Website", status: "Verified", title: "A second Omi article states 1,200 minutes and $199/year", summary: "A separate preserved Omi article says the free plan includes 1,200 cloud minutes per month and describes Unlimited as $19 per month or $199 per year.", publicFile: true, publicPath: "/evidence/website/OMI-WEB-002-umevo-article-199-and-1200.png", publicLabel: "View public article screenshot ↗" },
  { id: "OMI-SEARCH-001", date: "Preserved August 23, 2026", source: "Google results screenshot", category: "Search record", status: "Verified", title: "Eight visible Omi-domain results mention the earlier price", summary: "The supplied Google results screenshot shows eight visible Omi AI pages whose snippets mention $199 per year, with several also mentioning 1,200 minutes. Search snippets can be cached or stale, so this record supports discoverability and repetition of the representation but does not independently prove each underlying page's contents on the capture date.", publicFile: true, publicPath: "/evidence/search/OMI-SEARCH-001-google-results-199-omi-me.png", publicLabel: "View public search screenshot ↗" },
  { id: "OMI-APP-001", date: "August 21, 2026", source: "Omi app screenshot", category: "App", status: "Verified", title: "$269.91 annual Unlimited price shown in app", summary: "The supplied screenshot shows Yearly selected and the Unlimited plan listed at $22 per month and $269.91 for 12 months. The original file metadata records August 21, 2026 at 2:04 PM Eastern, consistent with the visible status-bar time.", publicFile: true, publicPath: "/evidence/app/OMI-APP-001-yearly-unlimited-269-91.png", publicLabel: "View public screenshot ↗" },
  { id: "OMI-EMAIL-000", date: "August 20, 2026", source: "Purchaser email to Omi Support", category: "Email", status: "Verified", title: "Initial request for annual-plan discount", summary: "The purchaser asked Omi Support for a 30% discount code for the yearly Unlimited subscription plan.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-000-initial-request-redacted.pdf" },
  { id: "OMI-EMAIL-001", date: "August 21, 2026", source: "Omi Support", category: "Email", status: "Verified", title: "Support states annual Unlimited is $199.99", summary: "Mohammed Mohsin calculated $19.99 monthly as $239.88 annually and contrasted it with $199.99 if paid annually.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-001-annual-price-redacted.pdf" },
  { id: "OMI-CALL-001", date: "August 22, 2026", source: "Purchaser recollection", category: "Telephone", status: "First-person account", title: "Support-number call; identity inferred afterward", summary: "The purchaser called a number ChatGPT presented in response to a request for an Omi support contact. After the call, public-record search results led him to infer that the person reached might have been COO Aarav Garg. The person did not identify himself by name, the call was not recorded, and the identity inference has not been independently verified.", publicFile: false },
  { id: "OMI-EMAIL-004", date: "August 22, 2026", source: "Omi Support", category: "Email", status: "Verified", title: "Support says 1,200 minutes are unavailable", summary: "Omi Support said a 1,200-minute monthly allowance was unavailable on any plan and offered either the app-priced Unlimited plan or a full refund.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-004-minutes-and-refund-options-redacted.pdf" },
  { id: "OMI-CHECKOUT-001", date: "August 22, 2026", source: "Omi hardware checkout screenshot", category: "Checkout", status: "Verified", title: "No affirmative terms acceptance visible at payment step", summary: "The captured checkout screen shows a “Pay now” button and footer links to the Refund policy, Shipping, Privacy policy, and Terms of service. No “I agree” checkbox or affirmative terms-acceptance statement is visible in this capture. The image alone does not establish whether another step existed or whether any terms are legally enforceable.", publicFile: true, publicPath: "/evidence/checkout/OMI-CHECKOUT-001-no-visible-affirmative-assent-redacted.png", publicLabel: "View redacted checkout screenshot ↗" },
  { id: "OMI-HELP-002", date: "Article dated November 15, 2025", source: "Omi Help Center screenshot", category: "Help center", status: "Verified", title: "Earlier Help Center version lists 1,200 minutes and $199/year", summary: "The purchaser identifies this as the Help Center version visible when the hardware was bought. It lists 1,200 Basic listening minutes per month and Unlimited at $199 per year or $19 per month. The article displays a November 15, 2025 date, but the image itself does not establish when the screenshot was captured.", publicFile: true, publicPath: "/evidence/help-center/OMI-HELP-002-earlier-1200-and-199.png", publicLabel: "View public Help Center screenshot ↗" },
  { id: "OMI-HELP-001", date: "Preserved August 22, 2026", source: "Omi Help Center screenshot", category: "Help center", status: "Verified", title: "Later Help Center version lists 300 Basic minutes", summary: "A later capture of the same Help Center URL displays “Updated today,” lists 300 Basic listening minutes per month, and adds a Plus tier with 1,500 minutes at $19 monthly or $161.91 annually. The capture documents the later page state; it does not establish why or in response to whom the page changed.", publicFile: true, publicPath: "/evidence/help-center/OMI-HELP-001-later-300-basic.png", publicLabel: "View public Help Center screenshot ↗" },
  { id: "OMI-AG-001", date: "August 22, 2026", source: "Pennsylvania Office of Attorney General confirmation email", category: "Regulatory filing", status: "Verified", title: "Consumer complaint receipt acknowledged", summary: "An automated confirmation states that the Office of Attorney General received the purchaser’s information and was reviewing it. This verifies receipt only; it is not a finding on the merits or an endorsement of the submitted allegations. The public excerpt omits personal data and the repeated complaint text.", publicFile: true, publicPath: "/evidence/regulatory/OMI-AG-001-complaint-confirmation-excerpt-redacted.pdf", publicLabel: "View redacted confirmation excerpt ↗" },
  { id: "OMI-WEBAPP-001", date: "August 23, 2026", source: "Omi web app account-page screenshot", category: "Web app", status: "Verified", title: "Basic Plan displays 1,200 monthly minutes", summary: "The Omi web app shows a Basic Plan monthly listening limit of 0 / 1,200 minutes, 1,200 minutes left, and “1,200 minutes of listening per month” under what is included. The public copy removes browser chrome, the desktop taskbar, and purchaser account details without altering the plan card.", publicFile: true, publicPath: "/evidence/app/OMI-WEBAPP-001-basic-plan-1200-minutes-redacted.png", publicLabel: "View redacted public screenshot ↗" },
  { id: "OMI-EMAIL-002", date: "August 23, 2026", source: "Omi Support", category: "Email", status: "Verified", title: "Omi acknowledges inconsistent published materials", summary: "Mohsin called his earlier $199.99 figure an error, identified the app price as live, and said the inconsistencies were raised internally for review.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-002-inconsistencies-and-rescission-redacted.pdf" },
  { id: "OMI-EMAIL-003", date: "August 23, 2026", source: "Omi Support", category: "Email", status: "Verified", title: "Order cancelled and $203.99 refunded", summary: "Omi stated that the full order was cancelled and refunded and that the in-transit device could be returned with a prepaid label or discarded. A follow-up stated the refund initiation time.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-003-refund-verification-redacted.pdf" },
  { id: "OMI-EMAIL-005", date: "August 23, 2026", source: "Omi automated refund notification", category: "Email", status: "Verified", title: "Automated notice records a $203.99 refund", summary: "Omi’s transaction email states that Order #21308 was refunded for $203.99, marks both the Omi device and Firmware Developer Kit as refunded, and shows a -$203.99 refund entry. The public copy redacts recipient, email, payment-card, and Gmail account details.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-005-refund-notification-redacted.pdf" },
  { id: "OMI-BANK-001", date: "August 23, 2026", source: "Credit union record", category: "Banking record", status: "Pending clarification", title: "$203.99 pending transaction", summary: "A pending transaction appeared after the refund communication. Its type had not yet been conclusively determined; this record does not characterize it as a new charge.", publicFile: false },
];

export const timeline = [
  ["Before / around August 12", "Earlier Help Center wording preserved", "The purchaser identifies this Help Center version as the one visible when he bought the hardware. It lists 1,200 Basic minutes and Unlimited at $199 per year or $19 per month; the screenshot itself does not establish its capture date.", "OMI-HELP-002"],
  ["August 12", "Order placed", "Order #21308 purchased for $203.99 while earlier Omi materials reportedly showed approximately $199 annually and 1,200 free monthly minutes.", "OMI-ORDER-001"],
  ["August 21", "Different price appears", "Before the hardware arrived, the Omi app displayed $269.91 for annual Unlimited service.", "OMI-APP-001"],
  ["August 21", "Support confirms $199.99", "Omi support wrote that Unlimited was $19.99 monthly, or $199.99 if purchased annually.", "OMI-EMAIL-001"],
  ["August 21–22", "Discrepancy raised", "The purchaser asked Omi to reconcile the app price with the earlier price and free-tier representations.", "OMI-EMAIL-001"],
  ["August 22", "Support-number call", "The purchaser called a number ChatGPT presented as an Omi support contact. Public-record results later led him to infer that the person reached might have been COO Aarav Garg. The person did not identify himself, and the inference is not independently verified.", "OMI-CALL-001"],
  ["August 22", "1,200-minute allowance declined", "Omi Support wrote that a 1,200-minute monthly allowance was unavailable on any plan and offered the app-priced plan or a refund.", "OMI-EMAIL-004"],
  ["August 22", "Checkout design preserved", "A screenshot of the Omi hardware payment step shows a Pay now button and footer policy links, with no affirmative terms-acceptance control visible in the captured screen.", "OMI-CHECKOUT-001"],
  ["August 22", "Later Help Center wording preserved", "A later capture of the same Help Center URL displays “Updated today,” lists 300 Basic minutes, and adds a 1,500-minute Plus tier. The capture does not establish what prompted the change.", "OMI-HELP-001"],
  ["August 22", "Complaint receipt acknowledged", "The Pennsylvania Office of Attorney General confirmed receipt and stated that the submitted information was being reviewed. This was an acknowledgment, not a merits determination.", "OMI-AG-001"],
  ["August 23", "Web app still shows 1,200 minutes", "A preserved account-page screenshot shows the Basic Plan with a 1,200-minute monthly listening limit, while the later Help Center capture lists 300.", "OMI-WEBAPP-001"],
  ["August 23", "Omi acknowledges inconsistencies", "Support withdrew the $199.99 figure, called the app price live, and said inconsistencies in published materials were referred for review.", "OMI-EMAIL-002"],
  ["August 23", "Order cancelled and refunded", "Omi stated that it cancelled the entire $203.99 order and did not require return of the shipped hardware.", "OMI-EMAIL-003"],
  ["August 23", "Automated refund notice issued", "Omi’s transaction notification recorded a $203.99 refund for Order #21308 and marked both purchased items as refunded.", "OMI-EMAIL-005"],
  ["August 23", "Bank entry awaits clarification", "A pending $203.99 transaction appeared. Its type was not yet confirmed.", "OMI-BANK-001"],
] as const;
export const nav = [["Timeline", "/timeline"], ["Pricing", "/pricing"], ["Evidence", "/evidence"], ["Correspondence", "/correspondence"], ["Omi’s position", "/omi-position"], ["Resources", "/resources"], ["About", "/about"]] as const;
