export type EvidenceStatus = "Verified" | "Awaiting public file" | "First-person account" | "Pending clarification";
export type EvidenceItem = { id: string; date: string; source: string; category: string; status: EvidenceStatus; title: string; summary: string; publicFile: boolean; publicPath?: string; publicLabel?: string; };

export const evidence: EvidenceItem[] = [
  { id: "OMI-ORDER-001", date: "August 12, 2026", source: "Omi account order record", category: "Order record", status: "Verified", title: "Order #21308 totaled $203.99", summary: "The order record is straightforward: $129 for the Omi device after a $50 discount, $59.99 for the Firmware Developer Kit, and $15 shipping. I removed contact, payment, tracking, and order-access details from the public copy.", publicFile: true, publicPath: "/evidence/orders/OMI-ORDER-001-order-21308-redacted.pdf", publicLabel: "Open the redacted order ↗" },
  { id: "OMI-WEB-001", date: "Article dated January 15, 2026", source: "Omi website article screenshot", category: "Website", status: "Verified", title: "Omi article: $199 a year and 1,200 free minutes", summary: "This Omi article says customers get 1,200 free listening minutes each month. It puts Unlimited at $199 a year, or about $16 a month with two months free.", publicFile: true, publicPath: "/evidence/website/OMI-WEB-001-sales-article-199-and-1200.png", publicLabel: "Open the Omi article screenshot ↗" },
  { id: "OMI-WEB-002", date: "Preserved August 23, 2026", source: "Omi website article screenshot", category: "Website", status: "Verified", title: "Another Omi article repeats $199 and 1,200 minutes", summary: "This is a separate Omi page saying the free plan has 1,200 cloud minutes a month and Unlimited costs $19 monthly or $199 yearly. The numbers were not confined to one stray page.", publicFile: true, publicPath: "/evidence/website/OMI-WEB-002-umevo-article-199-and-1200.png", publicLabel: "Open the second Omi article ↗" },
  { id: "OMI-SEARCH-001", date: "Preserved August 23, 2026", source: "Google results screenshot", category: "Search record", status: "Verified", title: "Eight visible Omi results repeat the earlier price", summary: "The screenshot shows eight Omi pages in one Google search, all with snippets mentioning $199 a year. Several also mention 1,200 minutes. Google snippets can lag behind a changed page, so use this as evidence of how widespread and discoverable the claim was, not as proof of what every page said that day.", publicFile: true, publicPath: "/evidence/search/OMI-SEARCH-001-google-results-199-omi-me.png", publicLabel: "Open the Google results screenshot ↗" },
  { id: "OMI-APP-001", date: "August 21, 2026", source: "Omi app screenshot", category: "App", status: "Verified", title: "The app asks $269.91 for annual Unlimited", summary: "With Yearly selected, the app lists Unlimited at $22 a month and $269.91 for 12 months. The original metadata says August 21 at 2:04 PM Eastern, matching the time visible in the screenshot.", publicFile: true, publicPath: "/evidence/app/OMI-APP-001-yearly-unlimited-269-91.png", publicLabel: "Open the app screenshot ↗" },
  { id: "OMI-EMAIL-000", date: "August 20, 2026", source: "Purchaser email to Omi Support", category: "Email", status: "Verified", title: "I asked support for an annual-plan discount", summary: "Before discovering the larger price problem, I asked Omi Support for a 30% discount code for annual Unlimited.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-000-initial-request-redacted.pdf" },
  { id: "OMI-EMAIL-001", date: "August 21, 2026", source: "Omi Support", category: "Email", status: "Verified", title: "Support puts $199.99 in writing", summary: "Mohammed Mohsin did the math in the email: $19.99 monthly would total $239.88, while paying annually would cost $199.99.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-001-annual-price-redacted.pdf" },
  { id: "OMI-DISCORD-001", date: "August 21, 2026", source: "Purchaser recollection", category: "Discord", status: "First-person account", title: "I recall Nik discussing a possible $40 monthly price", summary: "I recall challenging the increase in Omi’s Discord and Nik Shevchenko responding that the new price was still lower than he wanted, with a possible price around $40 per month. No screenshot is in the archive yet, so this is my recollection rather than a verified quotation.", publicFile: false },
  { id: "OMI-CALL-001", date: "August 22, 2026", source: "Purchaser recollection", category: "Telephone", status: "First-person account", title: "I called a number I believed was Omi support", summary: "ChatGPT gave me the number when I asked for Omi support. After the call, a public-record search led me to think I may have reached COO Aarav Garg. The person never gave me his name, I did not record the call, and I cannot independently prove who answered.", publicFile: false },
  { id: "OMI-EMAIL-004", date: "August 22, 2026", source: "Omi Support", category: "Email", status: "Verified", title: "Support says 1,200 minutes are not available", summary: "Omi Support told me no plan could provide the 1,200-minute monthly allowance and gave me two choices: pay the app price for Unlimited or take a full refund.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-004-minutes-and-refund-options-redacted.pdf" },
  { id: "OMI-CHECKOUT-001", date: "August 22, 2026", source: "Omi hardware checkout screenshot", category: "Checkout", status: "Verified", title: "The payment screen shows no agreement checkbox", summary: "The checkout capture has a Pay now button and policy links in the footer. It does not show an I agree checkbox or any other clear act of accepting the terms. The image cannot prove whether another checkout step existed or settle whether any term is enforceable.", publicFile: true, publicPath: "/evidence/checkout/OMI-CHECKOUT-001-no-visible-affirmative-assent-redacted.png", publicLabel: "Open the redacted checkout screenshot ↗" },
  { id: "OMI-HELP-002", date: "Article dated November 15, 2025", source: "Omi Help Center screenshot", category: "Help center", status: "Verified", title: "Earlier Help page: 1,200 minutes and $199 a year", summary: "I identify this as the Help Center version visible when I bought the hardware. It lists 1,200 Basic minutes each month and Unlimited at $199 yearly or $19 monthly. The page displays November 15, 2025, but the screenshot itself does not prove when I captured it.", publicFile: true, publicPath: "/evidence/help-center/OMI-HELP-002-earlier-1200-and-199.png", publicLabel: "Open the earlier Help Center screenshot ↗" },
  { id: "OMI-HELP-001", date: "Preserved August 22, 2026", source: "Omi Help Center screenshot", category: "Help center", status: "Verified", title: "Later Help page: Basic drops to 300 minutes", summary: "The same Help Center URL now says Updated today, lists only 300 Basic minutes, and adds a 1,500-minute Plus tier for $19 monthly or $161.91 annually. This proves the later page state. It does not prove what prompted the edit.", publicFile: true, publicPath: "/evidence/help-center/OMI-HELP-001-later-300-basic.png", publicLabel: "Open the later Help Center screenshot ↗" },
  { id: "OMI-HELP-003", date: "Preserved August 23, 2026", source: "Omi Help Center screenshot", category: "Help center", status: "Verified", title: "The changed Help page shows the complete new pricing", summary: "This longer capture shows Basic at 300 minutes, Plus at $19 monthly or $161.91 annually, and Unlimited at $29 monthly or $269.91 annually. Browser chrome and the taskbar were cropped away without changing the page content.", publicFile: true, publicPath: "/evidence/help-center/OMI-HELP-003-later-complete-pricing.png", publicLabel: "Open the complete pricing screenshot ↗" },
  { id: "OMI-TERMS-001", date: "Accessed August 23, 2026", source: "Omi Terms of Sale, section 7.3", category: "Terms", status: "Verified", title: "Omi reserves the right to change subscription prices and features", summary: "Omi’s current terms say it may change subscription pricing, features, or term lengths prospectively. They say a customer who disagrees must cancel before the current term ends.", publicFile: true, publicPath: "https://www.omi.me/pages/terms-of-service", publicLabel: "Read Omi’s current terms ↗" },
  { id: "OMI-DATA-001", date: "Accessed August 23, 2026", source: "Omi Help Center", category: "Data and memories", status: "Verified", title: "Omi stores conversations and extracted memories in its cloud", summary: "Omi says each recording can produce a transcript, summary, insights, tasks, and saved memories. Conversations live in Omi’s cloud, and the system uses that history to answer questions about a user’s past.", publicFile: true, publicPath: "https://help.omi.me/en/articles/13153612-conversations-memories-and-chats", publicLabel: "Read Omi’s memory documentation ↗" },
  { id: "OMI-AG-001", date: "August 22, 2026", source: "Pennsylvania Office of Attorney General confirmation email", category: "Regulatory filing", status: "Verified", title: "Pennsylvania confirms receipt of my complaint", summary: "The automated email says the Attorney General’s office received my information and was reviewing it. That proves the complaint arrived. It is not a ruling, endorsement, or finding against Omi.", publicFile: true, publicPath: "/evidence/regulatory/OMI-AG-001-complaint-confirmation-excerpt-redacted.pdf", publicLabel: "Open the redacted confirmation ↗" },
  { id: "OMI-WEBAPP-001", date: "August 23, 2026", source: "Omi web app account-page screenshot", category: "Web app", status: "Verified", title: "The web app still shows 1,200 Basic minutes", summary: "The account page says 0 / 1,200 minutes, 1,200 minutes left, and 1,200 minutes of listening per month. That was still visible after support said no plan could offer 1,200. I removed the browser, taskbar, and account details without changing the plan card.", publicFile: true, publicPath: "/evidence/app/OMI-WEBAPP-001-basic-plan-1200-minutes-redacted.png", publicLabel: "Open the redacted web-app screenshot ↗" },
  { id: "OMI-EMAIL-002", date: "August 23, 2026", source: "Omi Support", category: "Email", status: "Verified", title: "Omi admits its published materials conflicted", summary: "Mohsin withdrew the $199.99 figure, said the app showed the live price, and acknowledged that I had found inconsistencies in Omi’s published materials.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-002-inconsistencies-and-rescission-redacted.pdf" },
  { id: "OMI-EMAIL-003", date: "August 23, 2026", source: "Omi Support", category: "Email", status: "Verified", title: "Omi cancels and refunds the full $203.99 order", summary: "Omi said it cancelled everything, refunded the full order, and did not require the device already in transit to come back. Support offered a prepaid label or said I could discard it.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-003-refund-verification-redacted.pdf" },
  { id: "OMI-EMAIL-005", date: "August 23, 2026", source: "Omi automated refund notification", category: "Email", status: "Verified", title: "The automated notice confirms a $203.99 refund", summary: "Omi’s transaction email marks both purchased items as refunded and shows a negative $203.99 entry. I removed the recipient, email, card, and Gmail account details from the public copy.", publicFile: true, publicPath: "/evidence/emails/OMI-EMAIL-005-refund-notification-redacted.pdf" },
  { id: "OMI-BANK-001", date: "August 23, 2026", source: "Credit union record", category: "Banking record", status: "Pending clarification", title: "A $203.99 bank entry was still pending", summary: "A pending $203.99 transaction appeared after the refund messages. I had not yet confirmed whether it was the refund or something else, so this record does not call it a new charge.", publicFile: false },
];

export const timeline = [
  ["Before / around August 12", "The Help Center advertises the old deal", "I identify this as the version I saw when I bought the hardware: 1,200 Basic minutes, $199 yearly Unlimited, and $19 monthly Unlimited. The screenshot itself does not prove its capture date.", "OMI-HELP-002"],
  ["August 12", "I place Order #21308", "I pay $203.99 for the Omi device, developer kit, and shipping after reading Omi pages that advertised $199 a year and 1,200 free minutes.", "OMI-ORDER-001"],
  ["August 21", "The app shows $269.91", "The hardware has not arrived yet. The annual Unlimited price in the app is now $69.92 higher than the figure support will put in writing that same day.", "OMI-APP-001"],
  ["August 21", "Support confirms $199.99 anyway", "Omi support writes that Unlimited costs $19.99 monthly or $199.99 when paid annually.", "OMI-EMAIL-001"],
  ["August 21 to 22", "I demand an explanation", "I ask Omi to reconcile the app price with the price and free allowance its own pages advertised.", "OMI-EMAIL-001"],
  ["August 21", "Discord raises the stakes", "I recall Nik Shevchenko saying the new price was still lower than he wanted and mentioning a possible price around $40 per month. No screenshot is public yet, so this remains a labeled first-person account.", "OMI-DISCORD-001"],
  ["August 22", "I call what I think is support", "ChatGPT gave me the number. A later public-record search made me think I may have reached COO Aarav Garg, but the person never identified himself and I cannot verify who answered.", "OMI-CALL-001"],
  ["August 22", "Support refuses the 1,200-minute allowance", "Omi says 1,200 monthly minutes are unavailable on any plan. My choices are the app-priced plan or a refund.", "OMI-EMAIL-004"],
  ["August 22", "The checkout screen has no agreement box", "The preserved payment screen shows Pay now and footer policy links. It does not show an I agree checkbox or another clear acceptance control.", "OMI-CHECKOUT-001"],
  ["August 22", "The Help Center now says 300", "A later capture of the same URL says Updated today, cuts Basic to 300 minutes, and adds a 1,500-minute Plus tier. The screenshot does not prove what prompted the edit.", "OMI-HELP-001"],
  ["August 22", "Pennsylvania receives my complaint", "The Attorney General’s office confirms receipt and says it is reviewing the submission. That is an acknowledgment, not a ruling.", "OMI-AG-001"],
  ["August 23", "The web app still says 1,200", "The Help Center says 300 and support says 1,200 is unavailable, yet my Omi web account still shows a 1,200-minute Basic limit.", "OMI-WEBAPP-001"],
  ["August 23", "Omi admits its materials conflict", "Support withdraws the $199.99 figure, calls the app price live, and says the inconsistencies I found have gone to the team for review.", "OMI-EMAIL-002"],
  ["August 23", "Omi cancels and refunds everything", "Omi refunds the full $203.99 order and says I do not have to return the hardware already on its way.", "OMI-EMAIL-003"],
  ["August 23", "The refund notice lands", "Omi’s automated email records the $203.99 refund and marks both items as refunded.", "OMI-EMAIL-005"],
  ["August 23", "One bank entry is still unclear", "A pending $203.99 transaction appears after the refund messages. I have not yet confirmed what type of transaction it is.", "OMI-BANK-001"],
] as const;
export const nav = [["Timeline", "/timeline"], ["Pricing", "/pricing"], ["Lock-in risk", "/lock-in"], ["Evidence", "/evidence"], ["Correspondence", "/correspondence"], ["Omi’s position", "/omi-position"], ["Resources", "/resources"], ["About", "/about"]] as const;
