import { evidence, timeline } from "./data";
import { Disclaimer, Footer, Header, Quote } from "./site-shell";
export default function Home() { return <><main><Header /><section className="hero" id="top"><div className="eyebrow"><span>THE DEAL CHANGED BEFORE DELIVERY</span><span>ORDER #21308</span></div><h1>Omi said <em>$199.</em><br />The app said <em>$269.91.</em></h1><p className="deck">I bought Omi hardware after Omi pages advertised a $199 yearly plan and 1,200 free minutes. While the package was still on its way, the app showed $269.91. Then the Help Center changed to 300 minutes. I kept the receipts.</p><div className="actions"><a className="button primary" href="/timeline">See how it happened <span aria-hidden="true">→</span></a><a className="button secondary" href="/evidence">See the receipts</a></div><p className="independent"><span aria-hidden="true">i</span> A customer runs this site. Omi does not.</p></section>
  <section className="numbers" aria-label="Main prices and free minutes"><article><span>PRICE OMI PUT IN WRITING</span><strong>$199.99</strong><p>Support confirmed it on August 21</p></article><article className="discrepancy"><span>PRICE SHOWN IN THE APP</span><strong>$269.91</strong><p>$69.92 more before the hardware even arrived</p></article><article><span>FREE MINUTES OMI ADVERTISED</span><strong>1,200</strong><p>Shown in Omi articles and the earlier Help Center</p></article><article className="discrepancy"><span>FREE MINUTES AFTER THE CHANGE</span><strong>300</strong><p>Three quarters of the free minutes gone</p></article></section>
  <section className="lockin-band section-space"><div className="section-heading"><span className="kicker">THE BIGGER RISK</span><h2>The device is cheap. Leaving may not be.</h2><p>The longer Omi keeps your conversations, tasks, and memories, the harder it may be to leave. Its current rules say it may change plan prices and features when it is time to renew.</p><a className="text-link" href="/lock-in">Why saved history can make leaving hard →</a></div><aside className="lockin-card"><span>OMI’S CURRENT RULES</span><strong>Prices and features may change.</strong><p>If you do not agree, Omi says you should cancel. That answer feels very different after you spend months building useful saved history.</p></aside></section>
  <section className="home-grid section-space" id="evidence"><div className="section-heading"><span className="kicker">THEN SUPPORT ADMITTED THE MESS</span><h2>Mohsin agreed that Omi’s information did not match.</h2><p>After I pushed back, Mohsin took back the $199.99 price. He said the app had the correct price and that the team would review the Omi pages that did not match.</p></div><Quote cite="Mohammed Mohsin, Omi Support · August 23, 2026" id="OMI-EMAIL-002">The $199.99 annual figure in my message of 21 August was my error and I should not have quoted it to you as I did. The price shown in the app is the live one. I have raised the inconsistencies you identified in our published materials with the team for review.</Quote></section>
  <section className="about-home section-space"><div><span className="kicker">WHY I BUILT OMI.WTF</span><h2>A $70 dispute got weird fast.</h2></div><div className="about-home-copy"><p>I asked Omi to honor the price and minutes I had seen. Instead, Omi refunded the entire $203.99 order. Support said I could return the device when it arrived or throw it away.</p><p>Omi chose to cancel the sale instead of covering a first-year gap of about $70. That made this bigger than my order. If Omi can change the price after customers build saved history inside its service, every owner has a reason to pay attention.</p><p>So I kept the receipts, shared Omi’s explanation, and built a place where other customers can compare what happened to them.</p><a className="text-link" href="/about">Read why I am doing this →</a></div></section>
  <section className="timeline-preview section-space" id="timeline"><div className="section-heading row"><div><span className="kicker">WATCH THE DEAL MOVE</span><h2>The package was moving.<br />So were the terms.</h2></div><a className="text-link" href="/timeline">Read the full timeline →</a></div><div className="mini-timeline">{timeline.slice(0, 4).map(([date, title, text, id], i) => <article key={`${date}-${title}`}><span className="sequence">0{i + 1}</span><div><time>{date}, 2026</time><h3>{title}</h3><p>{text}</p><a href={`/evidence#${id}`}>{id} ↗</a></div></article>)}</div></section>
  <section className="position-band" id="position"><div><span className="kicker light">OMI GETS ITS SAY</span><h2>Mohsin says the price was his mistake.</h2><p>Mohsin said he gave me the wrong price. He said the app had the correct price, the team would review the pages that did not match, and the whole order was refunded.</p></div><a className="button on-dark" href="/omi-position">Read Omi’s answer →</a></section>
  <section className="review-band section-space"><Disclaimer /><div><span className="kicker">RECEIPTS, NOT RUMORS</span><h2>{evidence.length} records and counting</h2><p>The emails, screenshots, order, refund notice, and changed pages are all here. I removed private details but kept the facts.</p><a className="text-link" href="/evidence">See all the records →</a></div></section>
  <section className="share-band" id="share"><span className="kicker">DID OMI CHANGE THE DEAL ON YOU?</span><h2>You may not be the only one.</h2><p>If you bought hardware after seeing the same price or free-minute promise, tell me what happened. Keep your screenshots, emails, and receipts.</p><a className="button light-button" href="/experiences">Compare your story →</a></section></main><Footer /></>; }
