import { evidence, timeline } from "./data";
import { Disclaimer, Footer, Header, Quote } from "./site-shell";
export default function Home() { return <><main><Header /><section className="hero" id="top"><div className="eyebrow"><span>DOCUMENTED PRICING CHANGE</span><span>ORDER #21308</span></div><h1>Omi advertised <em>$199.</em><br />The app showed <em>$269.91.</em></h1><p className="deck">A documented timeline of subscription pricing, changing service limits, customer correspondence, and what happened when one purchaser asked Omi to honor the price he says influenced his purchase.</p><div className="actions"><a className="button primary" href="/timeline">View the timeline <span aria-hidden="true">→</span></a><a className="button secondary" href="/evidence">Examine the evidence</a></div><p className="independent"><span aria-hidden="true">i</span> Independently operated. Not affiliated with, endorsed by, or operated by Omi or Based Hardware, Inc.</p></section>
  <section className="numbers" aria-label="Key pricing figures"><article><span>ANNUAL PRICE REPRESENTED</span><strong>$199.99</strong><p>Confirmed in writing by Omi support on August 21</p></article><article className="discrepancy"><span>PRICE SHOWN IN APP</span><strong>$269.91</strong><p>$69.92 higher than the written support representation</p></article><article><span>FREE MINUTES REPRESENTED</span><strong>1,200</strong><p>Monthly minutes reportedly shown in earlier materials</p></article><article className="discrepancy"><span>FREE MINUTES LATER LISTED</span><strong>300</strong><p>A 75% reduction in the published allowance</p></article></section>
  <section className="home-grid section-space" id="evidence"><div className="section-heading"><span className="kicker">THE CENTRAL DOCUMENT</span><h2>Omi acknowledged inconsistent published materials.</h2><p>The August 23 email does not resolve every question. It does confirm that the earlier $199.99 support statement was wrong and that Omi’s published materials contained inconsistencies.</p></div><Quote cite="Mohammed Mohsin, Omi Support · August 23, 2026" id="OMI-EMAIL-002">The $199.99 annual figure in my message of 21 August was my error and I should not have quoted it to you as I did. The price shown in the app is the live one. I have raised the inconsistencies you identified in our published materials with the team for review.</Quote></section>
  <section className="timeline-preview section-space" id="timeline"><div className="section-heading row"><div><span className="kicker">WHAT HAPPENED</span><h2>Nine dated events.<br />One unresolved question.</h2></div><a className="text-link" href="/timeline">Full timeline →</a></div><div className="mini-timeline">{timeline.slice(0, 4).map(([date, title, text, id], i) => <article key={`${date}-${title}`}><span className="sequence">0{i + 1}</span><div><time>{date}, 2026</time><h3>{title}</h3><p>{text}</p><a href={`/evidence#${id}`}>{id} ↗</a></div></article>)}</div></section>
  <section className="position-band" id="position"><div><span className="kicker light">FAIRNESS MATTERS</span><h2>What Omi says</h2><p>Omi says the $199.99 support statement was an error, the app displayed the live price, discrepancies were referred for internal review, and the purchaser received a complete refund.</p></div><a className="button on-dark" href="/omi-position">Read Omi’s position →</a></section>
  <section className="review-band section-space"><Disclaimer /><div><span className="kicker">PUBLIC ARCHIVE STATUS</span><h2>{evidence.length} indexed records</h2><p>Public evidence files are being prepared for privacy review and redaction. The index already distinguishes verified correspondence, first-person recollection, and unresolved banking information.</p><a className="text-link" href="/evidence">Browse evidence index →</a></div></section>
  <section className="share-band" id="share"><span className="kicker">DID YOU BUY AN OMI?</span><h2>Compare your experience.</h2><p>If you saw similar pricing or free-minute representations, you can submit a documented account for private review. Nothing is published automatically.</p><a className="button light-button" href="/experiences">Share your experience →</a></section></main><Footer /></>; }
