import { evidence, timeline } from "./data";
import { Disclaimer, Footer, Header, Quote } from "./site-shell";
export default function Home() { return <><main><Header /><section className="hero" id="top"><div className="eyebrow"><span>THE DEAL CHANGED BEFORE DELIVERY</span><span>ORDER #21308</span></div><h1>Omi said <em>$199.</em><br />The app said <em>$269.91.</em></h1><p className="deck">I bought Omi hardware after Omi pages advertised a $199 annual plan and 1,200 free minutes. While the package was still on its way, the app showed $269.91. Then the Help Center changed to 300 minutes. I kept the receipts.</p><div className="actions"><a className="button primary" href="/timeline">See how it happened <span aria-hidden="true">→</span></a><a className="button secondary" href="/evidence">See the receipts</a></div><p className="independent"><span aria-hidden="true">i</span> Customer-run and independent. This is not an Omi website.</p></section>
  <section className="numbers" aria-label="Key pricing figures"><article><span>THE PRICE OMI PUT IN WRITING</span><strong>$199.99</strong><p>Support confirmed it on August 21</p></article><article className="discrepancy"><span>THE PRICE THAT APPEARED IN THE APP</span><strong>$269.91</strong><p>$69.92 more before the hardware even arrived</p></article><article><span>FREE MINUTES OMI PUBLISHED</span><strong>1,200</strong><p>Visible across Omi articles and the earlier Help Center</p></article><article className="discrepancy"><span>FREE MINUTES IN THE UPDATED HELP PAGE</span><strong>300</strong><p>Three quarters of the allowance gone</p></article></section>
  <section className="lockin-band section-space"><div className="section-heading"><span className="kicker">THE BIGGER RISK</span><h2>The device is cheap. Leaving may not be.</h2><p>The longer Omi stores conversations, summaries, tasks, and memories, the more a price increase can feel like a toll on a customer’s own history. Omi’s current terms reserve the right to change subscription pricing and features at renewal.</p><a className="text-link" href="/lock-in">Why the memory archive changes the stakes →</a></div><aside className="lockin-card"><span>OMI’S CURRENT TERMS</span><strong>Prices and features may change.</strong><p>If a customer does not agree, Omi’s stated answer is to cancel before renewal. That answer gets less satisfying after someone has spent months building a useful archive.</p></aside></section>
  <section className="home-grid section-space" id="evidence"><div className="section-heading"><span className="kicker">THEN OMI ADMITTED THE MESS</span><h2>The inconsistency was real. Omi said so.</h2><p>After I pushed back, support withdrew the $199.99 figure, called the app price live, and said the conflicting published materials had been sent to the team for review.</p></div><Quote cite="Mohammed Mohsin, Omi Support · August 23, 2026" id="OMI-EMAIL-002">The $199.99 annual figure in my message of 21 August was my error and I should not have quoted it to you as I did. The price shown in the app is the live one. I have raised the inconsistencies you identified in our published materials with the team for review.</Quote></section>
  <section className="timeline-preview section-space" id="timeline"><div className="section-heading row"><div><span className="kicker">WATCH THE DEAL MOVE</span><h2>The package was moving.<br />So were the terms.</h2></div><a className="text-link" href="/timeline">Read the full timeline →</a></div><div className="mini-timeline">{timeline.slice(0, 4).map(([date, title, text, id], i) => <article key={`${date}-${title}`}><span className="sequence">0{i + 1}</span><div><time>{date}, 2026</time><h3>{title}</h3><p>{text}</p><a href={`/evidence#${id}`}>{id} ↗</a></div></article>)}</div></section>
  <section className="position-band" id="position"><div><span className="kicker light">OMI GETS ITS SAY</span><h2>Omi says it was a mistake.</h2><p>Omi says support quoted the wrong price, the app had the live price, the conflicting pages went to the team for review, and the entire order was refunded.</p></div><a className="button on-dark" href="/omi-position">Read Omi’s explanation →</a></section>
  <section className="review-band section-space"><Disclaimer /><div><span className="kicker">RECEIPTS, NOT RUMORS</span><h2>{evidence.length} records and counting</h2><p>Emails, screenshots, order records, refund notices, and the pages that changed are all here. Private details are removed. The substance is not.</p><a className="text-link" href="/evidence">Open the evidence archive →</a></div></section>
  <section className="share-band" id="share"><span className="kicker">DID OMI CHANGE THE DEAL ON YOU?</span><h2>You may not be the only one.</h2><p>If you bought hardware after seeing the same price or free-minute promise, tell me what happened. Keep your screenshots, emails, and receipts.</p><a className="button light-button" href="/experiences">Compare your story →</a></section></main><Footer /></>; }
